-- https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts
-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet
--   פּ ﯟ   蘒練 some other good icons

return {
  kind = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
    Misc = "",
  },
  type = {
    Array = "",
    Number = "",
    String = "",
    Boolean = "",
    Object = "",
  },
  documents = {
    File = "",
    FileWithContent = "",
    Files = "",
    NewFile = "",
    Symlink = "",
    Folder = "",
    OpenFolder = "",
    EmptyFolder = "",
    OpenEmptyFolder = "",
    SymlinkFolder = "",
    Archive = "",
  },
  git = {
    Add = "",
    Mod = "",
    Remove = "",
    Ignore = "",
    Rename = "",
    Diff = "",
    Repo = "",
    Branch = "",
    Merge = "",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = "",
    SmallCircle = "",
    Circle = "●",
    FilledCircle = "◍",
    UnfilledCircle = "○",
    DashedCircle = "◌",
    BigCircle = "",
    BigUnfilledCircle = "",
    Close = "",
    Search = "",
    Lightbulb = "",
    Project = "",
    Dashboard = "",
    History = "",
    Comment = "",
    Bug = "",
    Code = "",
    Telescope = "",
    Gear = "",
    Package = "",
    List = "",
    SignIn = "",
    SignOut = "",
    NoteBook = "",
    Check = "",
    Fire = "",
    Note = "",
    BookMark = "",
    Pencil = "",
    -- ChevronRight = "",
    -- ChevronRight = ">",
    ChevronRight = "",
    Table = "",
    Calendar = "",
    CloudDownload = "",
    Terminal = "",
    ShiftWidth = "",
    Version = "",
    Trash = "",
  },
  debug = {
    Start = "",
    Pause = "",
    StepInto = "",
    StepOver = "",
    StepOut = "",
    StepBack = "",
    Restart = "",
    Stop = "",
  },
  diagnostics = {
    Error = "",
    Warning = "",
    Information = "",
    Question = "",
    ErrorOutline = "",
    WarningOutline = "",
    InformationOutline = "",
    QuestionOutline = "",
    Hint = "",
  },
  misc = {
    Robot = "",
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "",
    Package = "",
    CircuitBoard = "",
    Lightning = "",
    Keyboard = "",
    Lazy = "󰒲",
  },
}
